<a href="https://colab.research.google.com/github/aryankamboj0001/titanic-machine-learning-project/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

## Titanic Survival Prediction

This project predicts whether a passenger survived the Titanic disaster using Machine Learning.



In [8]:
df = sns.load_dataset("titanic")

In [9]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [10]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [12]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

## Data Preprocessing
- Handling missing values
- Encoding categorical variables


In [13]:
df.drop(['deck', 'embark_town','alive','class', 'who', 'adult_male'],axis=1,inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [15]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [16]:
df.dropna(subset='embarked',inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


## Model Training
Logistic Regression is used for binary classification.




In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
df.head(10)

survived  pclass     sex        age  sibsp  parch     fare embarked  alone
0         0       3    male  22.000000      1      0   7.2500        S  False
1         1       1  female  38.000000      1      0  71.2833        C  False
2         1       3  female  26.000000      0      0   7.9250        S   True
3         1       1  female  35.000000      1      0  53.1000        S  False
4         0       3    male  35.000000      0      0   8.0500        S   True
5         0       3    male  29.699118      0      0   8.4583        Q   True
6         0       1    male  54.000000      0      0  51.8625        S   True
7         0       3    male   2.000000      3      1  21.0750        S  False
8         1       3  female  27.000000      0      2  11.1333        S  False
9         1       2  female  14.000000      1      0  30.0708        C  False

In [20]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])  # S=2,Q=1,C=0

In [21]:
df.head(10)

survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.000000      1      0   7.2500         2  False
1         1       1    0  38.000000      1      0  71.2833         0  False
2         1       3    0  26.000000      0      0   7.9250         2   True
3         1       1    0  35.000000      1      0  53.1000         2  False
4         0       3    1  35.000000      0      0   8.0500         2   True
5         0       3    1  29.699118      0      0   8.4583         1   True
6         0       1    1  54.000000      0      0  51.8625         2   True
7         0       3    1   2.000000      3      1  21.0750         2  False
8         1       3    0  27.000000      0      2  11.1333         2  False
9         1       2    0  14.000000      1      0  30.0708         0  False

In [22]:
df.astype(int)

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [23]:
x = df.drop('survived',axis=1)
y = df["survived"]

In [24]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.20,random_state=42)

In [25]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

LogisticRegression()

## Model Evaluation
Accuracy score is used to evaluate performance.


In [26]:
y_pred = model.predict(x_test)

In [27]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [28]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [30]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [31]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [32]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [34]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)


In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [37]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [38]:
accuracy_score(y_test,y_pred_knn)

0.7921348314606742

In [39]:
confusion_matrix(y_test,y_pred_knn)

array([[89, 20],
       [17, 52]])

In [40]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



In [41]:
from sklearn.naive_bayes import GaussianNB

In [42]:
modelNB = GaussianNB()

In [43]:
modelNB.fit(x_train,y_train)

GaussianNB()

In [44]:
y_pred_NB = modelNB.predict(x_test)

In [45]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [46]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [47]:
accuracy_score(y_test,y_pred_NB)

0.7752808988764045

In [48]:
confusion_matrix(y_test,y_pred_NB)

array([[84, 25],
       [15, 54]])

In [49]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [50]:
from sklearn.tree import DecisionTreeClassifier

In [51]:
model_DT = DecisionTreeClassifier(random_state=42)

In [52]:
model_DT.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [53]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [54]:
y_pred_DT

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1])

In [55]:
accuracy_score(y_test,y_pred_DT)

0.7528089887640449

In [56]:
confusion_matrix(y_test,y_pred_DT)

array([[87, 22],
       [22, 47]])

In [57]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80       109
           1       0.68      0.68      0.68        69

    accuracy                           0.75       178
   macro avg       0.74      0.74      0.74       178
weighted avg       0.75      0.75      0.75       178



In [58]:
from sklearn.svm import SVC

In [59]:
model_svm = SVC(kernel = 'rbf')

In [60]:
model_svm.fit(x_train_scaled,y_train)

SVC()

In [61]:
y_pred_svm = model_svm.predict(x_test_scaled)

In [62]:
accuracy_score(y_test,y_pred_svm)

0.8258426966292135

In [63]:
confusion_matrix(y_test,y_pred_svm)

array([[96, 13],
       [18, 51]])

In [64]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178



In [65]:
# cross validation

In [66]:
df

survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2  False
1           1       1    0  38.000000      1      0  71.2833         0  False
2           1       3    0  26.000000      0      0   7.9250         2   True
3           1       1    0  35.000000      1      0  53.1000         2  False
4           0       3    1  35.000000      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2   True
887         1       1    0  19.000000      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  26.000000      0      0  30.0000         0   True
890         0       3    1  32.000000      0      0   7.7500         1   True

[889 rows x 9 columns]

In [67]:
x = df.drop('survived',axis=1)
y = df['survived']

In [68]:
from sklearn.model_selection import cross_val_score

In [69]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [70]:
scores = cross_val_score(model_svm,x_scaled,y,cv=5,scoring='accuracy')    #for svm

In [71]:
scores

array([0.83146067, 0.82022472, 0.81460674, 0.80898876, 0.86440678])

In [72]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]


In [73]:
print(scores.mean())

0.8279375357074844


In [74]:
scores_2 = cross_val_score(model_DT,x_scaled,y,cv=5,scoring='accuracy')    # for decision tress
print(scores_2)

[0.75280899 0.75842697 0.78651685 0.73595506 0.82485876]


## Conclusion
The Logistic Regression model successfully predicts passenger survival with reasonable accuracy. The model can be improved further using advanced algorithms.
